version: "3"

services:
  mysql:
    image: mysql:8.0
    container_name: inspire_dream_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}  
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3020:3306"
    volumes:
      - database_storage:/var/lib/mysql

  app:
    build: .
    image: inspire_dream_backend:latest
    container_name: inspire_dream_backend
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    ports:
      - "3010:${BACKEND_PORT}"
    depends_on:
      - mysql
    volumes:
      - backend_storage:/usr/src/app/storage

volumes:
  database_storage:
  backend_storage:
